#!/usr/bin/expect -f

set timeout 30
set user "sirangkul"
set host "89.233.105.92"
set password "Sfgxjs4H38DQb7K"
set db_user "sirangkul"
set db_pass "jUSlAmnIagcSUz4"

spawn ssh -o StrictHostKeyChecking=accept-new $user@$host
expect "password:"
send "$password\r"

expect -re "(\\\$|#) $"
send "mysql -u $db_user -p$db_pass sirangkul -e \"SHOW TABLES; SELECT COUNT(*) FROM users;\" \r"

expect -re "(\\\$|#) $"
send "exit\r"
expect eof
