#!/usr/bin/expect -f
set timeout 30
set host "89.233.105.92"
set user "sirangkul"
set pass "Sfgxjs4H38DQb7K"

spawn ssh -o StrictHostKeyChecking=no $user@$host "echo '<?php echo \"Nginx Mapping OK\"; ?>' > /home/sirangkul/apps/sirangkul/api-sirangkul/public/test.php"
expect "password:"
send "$pass\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$host "curl -s https://sirangkul.man2kotamakassar.sch.id/api/test.php"
expect "password:"
send "$pass\r"
expect eof
